### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by DutchUser** [r-clancy/PlugMan#30]
Server Version: Spigot 1.9.4

22.05 20:25:12 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin PlugMan v2.1.1 generated an exception while executing task 63
22.05 20:25:12 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
22.05 20:25:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
22.05 20:25:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
22.05 20:25:12 [Server] INFO at java.lang.Thread.run(Unknown Source)
22.05 20:25:12 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
22.05 20:25:12 [Server] INFO at org.mcstats.Metrics.postPlugin(Metrics.java:335)
22.05 20:25:12 [Server] INFO at org.mcstats.Metrics.access$400(Metrics.java:57)
22.05 20:25:12 [Server] INFO at org.mcstats.Metrics$1.run(Metrics.java:223)
22.05 20:25:12 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
22.05 20:25:12 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
22.05 20:25:12 [Server] INFO ... 3 more

**Comment by r-clancy** [comment]
Try the following dev build, I reverted a commit that most likely caused the issue.

http://ci.ryan-clancy.com/job/PlugMan/branch/dev/1/artifact/target/PlugMan.jar

**Comment by DutchUser** [comment]
Still error: http://pastebin.com/r7QVfyCn (Not sure if its the same)

**Comment by r-clancy** [comment]
I can't seem to re-produce this with either the current release (2.1.1) or the dev. build provided above - I'll have to take a deeper look into it when I have some time to spare (it doesn't affect functionality, just some log spam).

If anyone else is experiencing this issue, please do let me know.

**Comment by DutchUser** [comment]
I think its an bukit related bug:

Caused by: java.lang.NoSuchMethodError: org.**bukkit**.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;

**Comment by DutchUser** [comment]
Í close this ticket because it seems that its was an bukkit related bug. After updateing to 1.10 this error dont come anymore in my console.
